specVersion: 0.2.0
name: subql-karua
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c'
  endpoint: wss://acala-polkadot.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/acala-dictionary
  chaintypes:
    file: ./types.json
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleTransferCurrency
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Transferred
        - handler: handleFailedTransfers
          kind: substrate/CallHandler
# giving error at block 1,412,702 so going to index from next block e.g 1,412,703