specVersion: 0.2.0
name: subql-shibuya
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xcc07acbee59e89a8bc99d87a24364b514d6ae657551338547b713444583eaac2'
  endpoint: wss://gladios.aresprotocol.io
  chaintypes:
    file: ./types.yaml
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer

# giving error at block 1,412,702 so going to index from next block e.g 1,412,703