specVersion: 0.2.0
name: subql-shibuya
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527'
  endpoint: wss://moonbeam-alpha.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/astar-dictionary
  chaintypes:
    file: "./types.yaml"
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer

