specVersion: 0.2.0
name: subql-shibuya
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x6254c948b5eb7199a112cb308be3385c39c8c942625540ac749c77fe2aebc299'
  endpoint: wss://contextfree.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/contextfree-dictionary
  chaintypes:
    file: ./types.yaml
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer

# giving error at block 1,412,702 so going to index from next block e.g 1,412,703