specVersion: 0.2.0
name: subql-shibuya
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: "0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe"
  endpoint: wss://kusama.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/kusama-dictionary
  
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer

# giving error at block 1,412,702 so going to index from next block e.g 1,412,703