specVersion: 0.2.0
name: subql-shibuya
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: "0xe81cddea5dc9954ccf7aa868d231082a2bab589dd4f81592c24c490fd2e231c8"
  endpoint: wss://neumann.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/neumann-dictionary
  chaintypes:
    file: ./types.yaml
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer

# giving error at block 1,412,702 so going to index from next block e.g 1,412,703